name: CI/CD Pipeline

# Trigger the workflow on push to develop and main branches and on pull requests
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: windows-latest  # Use Windows environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m pytest  # Adjust this command based on your test framework

    - name: Build project
      run: |
        python app.py build  # Adjust this command based on your build process
